namespace Revestik.Shared.ElectronicDocuments;

public sealed record ElectronicDocumentDiscountResponse(
    decimal Amount,
    string Code,
    string Nature);

public sealed record ElectronicDocumentTaxResponse(
    string TaxCode,
    string VatRateCode,
    decimal Rate,
    decimal Amount);

public sealed record ElectronicDocumentLineResponse(
    int Id,
    int LineNumber,
    string CabysCode,
    string CommercialCodeType,
    string CommercialCode,
    decimal Quantity,
    string UnitOfMeasure,
    string CommercialUnitOfMeasure,
    string Description,
    decimal UnitPrice,
    decimal GrossAmount,
    decimal Subtotal,
    decimal TaxableBase,
    decimal NetTax,
    decimal TotalLine,
    IReadOnlyList<ElectronicDocumentDiscountResponse> Discounts,
    IReadOnlyList<ElectronicDocumentTaxResponse> Taxes,
    string? CabysOfficialDescription = null,
    string? CabysTaxReference = null,
    string? CabysHierarchy = null,
    int? ClassificationCategoryId = null,
    string? ClassificationCategoryName = null,
    AccountingNature? ClassificationAccountingNature = null,
    OperationalDestination? OperationalDestination = null);

public sealed record HaciendaResponseDetailResponse(
    string MessageCode,
    string MessageStatus,
    string MessageDetail,
    decimal TotalTax,
    decimal TotalInvoice,
    DateTime ReceivedAtUtc);

public sealed record ElectronicDocumentDetailResponse(
    int Id,
    string Clave,
    ElectronicDocumentType DocumentType,
    string NumeroConsecutivo,
    DateTimeOffset FechaEmision,
    string IssuerName,
    string IssuerCommercialName,
    string IssuerIdentificationType,
    string IssuerIdentification,
    string IssuerPhoneNumber,
    string IssuerEmail,
    string IssuerAddress,
    string ReceiverName,
    string ReceiverIdentificationType,
    string ReceiverIdentification,
    string SaleConditionCode,
    int? CreditTermDays,
    string CurrencyCode,
    decimal ExchangeRate,
    decimal TotalTaxedServices,
    decimal TotalExemptServices,
    decimal TotalExoneratedServices,
    decimal TotalNonSubjectServices,
    decimal TotalTaxedGoods,
    decimal TotalExemptGoods,
    decimal TotalExoneratedGoods,
    decimal TotalNonSubjectGoods,
    decimal TotalTaxed,
    decimal TotalExempt,
    decimal TotalExonerated,
    decimal TotalNonSubject,
    decimal TotalSale,
    decimal TotalDiscounts,
    decimal TotalNetSale,
    decimal TotalTax,
    decimal TotalVatReturned,
    decimal TotalOtherCharges,
    decimal TotalDocument,
    ElectronicDocumentProcessingStatus ProcessingStatus,
    int? CategoryId,
    string? CategoryName,
    int? SupplierId,
    string? SupplierName,
    int? PurchaseId,
    DateTime ImportedAtUtc,
    DateTime? ProcessedAtUtc,
    IReadOnlyList<ElectronicDocumentLineResponse> Lines,
    HaciendaResponseDetailResponse? HaciendaResponse,
    string IssuerEconomicActivityCode = "",
    string ReceiverEconomicActivityCode = "",
    string? SuggestedCategoryLabel = null,
    string? SuggestedCategoryReason = null,
    AccountingNature? CategoryAccountingNature = null,
    OperationalDestination? OperationalDestination = null,
    int? SuggestedCategoryId = null,
    AccountingNature? SuggestedAccountingNature = null,
    OperationalDestination? SuggestedOperationalDestination = null,
    ClassificationConfidence? SuggestedConfidence = null,
    bool SuggestedHasConflict = false,
    bool HasLineOverrides = false);
